"""Browser abstraction.

Two small protocols keep the manager independent of Playwright so it can be
unit-tested with fakes:

- PageDriver : operations on one open page (navigate, read, click, fill, …).
- PageSource : produces fresh pages and owns the shared browser resource.
"""

from typing import Protocol


class PageDriver(Protocol):
    async def goto(self, url: str) -> None: ...
    async def text(self) -> str: ...
    async def title(self) -> str: ...
    async def url(self) -> str: ...
    async def click(self, selector: str) -> None: ...
    async def fill(self, selector: str, value: str) -> None: ...
    async def links(self, limit: int = 40) -> list[dict[str, str]]: ...
    async def screenshot(self, path: str) -> None: ...
    async def close(self) -> None: ...


class PageSource(Protocol):
    async def new_page(self) -> PageDriver: ...
    async def close(self) -> None: ...
