"""NUL (U+0000) must never reach the database.

Postgres rejects it in both `text` and `jsonb`; SQLite — which this suite runs
on — accepts it silently. So these tests deliberately assert on the *stripped
value*, which the column type produces on every dialect, rather than on an
error that only Postgres would raise.
"""

import pytest
from sqlalchemy import JSON, String, Text
from sqlalchemy.exc import DBAPIError, SQLAlchemyError

from claw.db.types import NulSafeJSON, NulSafeString, NulSafeText, _scrub
from claw.i18n import t


def test_nul_is_stripped_from_text_and_string_binds():
    for column in (NulSafeText(), NulSafeString(255)):
        assert column.process_bind_param("a\x00b", None) == "ab"


def test_clean_strings_pass_through_untouched():
    # The fast path must not corrupt ordinary content, including Thai, which is
    # multi-byte and where a bad replace would be very visible.
    for value in ("plain", "สวัสดีครับ", "", "tab\tnewline\n"):
        assert NulSafeText().process_bind_param(value, None) == value


def test_non_string_binds_pass_through():
    # None must stay None so the impl type's own NULL handling still applies.
    for value in (None, 42, True):
        assert NulSafeText().process_bind_param(value, None) is value


def test_nul_is_stripped_recursively_from_json_values_and_keys():
    payload = {
        "k\x00ey": "v\x00alue",
        "nested": {"deep": ["a\x00", {"x": "b\x00"}]},
        "untouched": [1, None, True, 2.5],
    }
    assert NulSafeJSON().process_bind_param(payload, None) == {
        "key": "value",
        "nested": {"deep": ["a", {"x": "b"}]},
        "untouched": [1, None, True, 2.5],
    }


def test_json_none_is_preserved():
    assert NulSafeJSON().process_bind_param(None, None) is None


def test_scrub_leaves_clean_scalars_identical():
    assert _scrub(None) is None
    assert _scrub(7) == 7


def test_column_types_still_render_as_their_underlying_sql_types():
    # The aliasing in models.py must not change emitted DDL, or Alembic would
    # want a migration for every column in the schema.
    assert isinstance(NulSafeText().impl, Text)
    assert isinstance(NulSafeJSON().impl, JSON)
    assert isinstance(NulSafeString(64).impl, String)
    # The length argument has to survive the TypeDecorator wrapper.
    assert NulSafeString(64).impl.length == 64


def test_autogenerated_migrations_render_plain_sqlalchemy_types():
    # Left alone, Alembic renders these as claw.db.types.NulSafeText() and adds
    # no import for it — script.py.mako only supplies `op` and `sa`. Since
    # lifespan() runs `alembic upgrade head`, that NameError would land as a
    # boot failure long after whoever ran --autogenerate had moved on.
    import sqlalchemy as sa
    from alembic.autogenerate import render_python_code
    from alembic.operations import ops

    from claw.db.types import render_migration_type

    code = render_python_code(
        ops.UpgradeOps(
            ops=[
                ops.AddColumnOp("messages", sa.Column("a", NulSafeText())),
                ops.AddColumnOp("messages", sa.Column("b", NulSafeString(64))),
                ops.AddColumnOp("messages", sa.Column("c", NulSafeJSON())),
            ]
        ),
        render_item=render_migration_type,
    )
    assert "claw.db.types" not in code
    assert "sa.Text()" in code and "sa.String(length=64)" in code and "sa.JSON()" in code
    # The rendered column expressions must be evaluable with only `sa` bound,
    # which is the whole namespace a generated migration actually has.
    for line in code.splitlines():
        if line.strip().startswith("op.add_column("):
            eval(line.strip().replace("op.add_column(", "(", 1), {"sa": sa})


@pytest.mark.parametrize("column_type", [NulSafeString, NulSafeText, NulSafeJSON])
def test_each_column_type_declares_its_own_cache_ok(column_type):
    # SQLAlchemy reads cache_ok from the class's OWN __dict__, so inheriting it
    # from a shared base silently disables the compiled-statement cache for
    # every column using the type. Missing it is a pure performance regression
    # with no failing behavior, so it has to be asserted rather than noticed.
    assert column_type.__dict__.get("cache_ok") is True


@pytest.mark.parametrize("role", ["assistant", "tool"])
async def test_message_with_nul_in_content_and_meta_persists(stores, role):
    """The production failure: PyMuPDF text extraction emits a NUL, which then
    reaches MessageStore.append via tool output and crashes the whole turn."""
    session = await stores["sessions"].create(user_id="u1", title="t")
    await stores["messages"].append(
        session.id,
        [{"role": role, "content": "PDF text\x00here", "meta": {"artifacts": ["a\x00.pdf"]}}],
    )

    stored = await stores["messages"].recent(session.id)
    assert stored[0]["content"] == "PDF texthere"
    assert "\x00" not in stored[0]["content"]


def test_a_storage_failure_is_not_reported_as_an_unreachable_model():
    """runtime._process_turn wraps the whole turn, so a failed transcript write
    lands in the same handler as a provider outage. asyncpg errors surface as
    DBAPIError, so that is what the branch keys on."""
    assert issubclass(DBAPIError, SQLAlchemyError)
    for locale in ("en", "th"):
        assert t("error.save", locale) != t("error.llm", locale, reason=t("reason.internal", locale))
    # The English wording must not blame the model, or the distinction is lost.
    assert "could not be saved" in t("error.save", "en")


async def test_session_title_with_nul_persists(stores):
    # Titles are model-generated, so they are an untrusted-text path too.
    await stores["sessions"].create(user_id="u1", title="Sum\x00mary")
    listed = await stores["sessions"].list_for_user("u1")
    assert all("\x00" not in s.title for s in listed)
