"""Add isolated Sbot mode without changing legacy conversation rows."""

from alembic import op
import sqlalchemy as sa

revision = "f0a1b2c3d4e5"
down_revision = "c6d7e8f9a0b1"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "users",
        sa.Column("sbot_heartbeat_interval_seconds", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("users", sa.Column("sbot_heartbeat_next_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("project_containers_enabled", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("project_container_limit", sa.Integer(), nullable=True))
    op.add_column(
        "user_groups",
        sa.Column("project_containers_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "user_groups", sa.Column("project_container_limit", sa.Integer(), nullable=False, server_default="0")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sbot_feedback",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("signal", sa.String(length=8), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("message_preview", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_feedback_user_id"), "sbot_feedback", ["user_id"], unique=False)
    op.create_index("ix_sbot_feedback_user_time", "sbot_feedback", ["user_id", "created_at"], unique=False)
    op.create_table(
        "sbot_blueprints",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_blueprints_owner_id"), "sbot_blueprints", ["owner_id"], unique=False)
    op.create_table(
        "sbot_bots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role_title", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.JSON(), nullable=True),
        sa.Column("charter", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("tool_allowlist", sa.JSON(), nullable=True),
        sa.Column("skill_ids", sa.JSON(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_bots_owner_id"), "sbot_bots", ["owner_id"], unique=False)
    op.create_index("ix_sbot_bots_owner_name", "sbot_bots", ["owner_id", "name"], unique=False)
    op.create_table(
        "sbot_memories",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sbot_memories_user_kind", "sbot_memories", ["user_id", "kind"], unique=False)
    op.create_index(op.f("ix_sbot_memories_user_id"), "sbot_memories", ["user_id"], unique=False)
    op.create_index("ix_sbot_memories_scope", "sbot_memories", ["scope", "scope_id", "kind"], unique=False)
    op.create_index(op.f("ix_sbot_memories_scope_id"), "sbot_memories", ["scope_id"], unique=False)
    op.create_table(
        "sbot_schedules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("cron", sa.String(length=64), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_schedules_user_id"), "sbot_schedules", ["user_id"], unique=False)
    op.create_table(
        "sbot_shares",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sbot_shares_user_id", "sbot_shares", ["user_id"], unique=False)
    op.create_index(op.f("ix_sbot_shares_token_hash"), "sbot_shares", ["token_hash"], unique=True)
    op.create_table(
        "sbot_blueprint_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("blueprint_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=120), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["blueprint_id"], ["sbot_blueprints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blueprint_id", "version", name="uq_blueprint_version"),
    )
    op.create_index(
        "ix_sbot_blueprint_versions_blueprint", "sbot_blueprint_versions", ["blueprint_id"], unique=False
    )
    op.create_table(
        "sbot_sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("bot_id", sa.String(length=32), nullable=True),
        sa.Column("group_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_consolidated_seq", sa.Integer(), nullable=False),
        sa.Column("consolidation_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["sbot_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_sessions_bot_id"), "sbot_sessions", ["bot_id"], unique=False)
    op.create_index(op.f("ix_sbot_sessions_group_id"), "sbot_sessions", ["group_id"], unique=False)
    op.create_index(op.f("ix_sbot_sessions_user_id"), "sbot_sessions", ["user_id"], unique=False)
    op.create_table(
        "sbot_bot_chat_groups",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("member_ids", sa.JSON(), nullable=False),
        sa.Column("leader_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["sbot_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sbot_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_sbot_bot_chat_groups_owner_id"), "sbot_bot_chat_groups", ["owner_id"], unique=False
    )
    op.create_table(
        "sbot_messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("speaker_bot_id", sa.String(length=32), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sbot_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_bot_id"],
            ["sbot_bots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sbot_messages_session_seq", "sbot_messages", ["session_id", "seq"], unique=False)
    op.create_index(
        op.f("ix_sbot_messages_speaker_bot_id"), "sbot_messages", ["speaker_bot_id"], unique=False
    )
    op.create_index(op.f("ix_sbot_messages_session_id"), "sbot_messages", ["session_id"], unique=False)
    op.create_table(
        "sbot_missions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=True),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=True),
        sa.Column("spent", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resumed_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sbot_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sbot_missions_session_id"), "sbot_missions", ["session_id"], unique=False)
    op.create_index(op.f("ix_sbot_missions_owner_id"), "sbot_missions", ["owner_id"], unique=False)
    op.create_index("ix_sbot_missions_status", "sbot_missions", ["status"], unique=False)
    op.create_table(
        "sbot_mission_blackboard",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("mission_id", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("written_by_node", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["sbot_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sbot_mission_blackboard_mission_id"), "sbot_mission_blackboard", ["mission_id"], unique=False
    )
    op.create_index(
        "ix_sbot_mission_blackboard_key", "sbot_mission_blackboard", ["mission_id", "key"], unique=True
    )
    op.create_table(
        "sbot_mission_nodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("mission_id", sa.String(length=32), nullable=False),
        sa.Column("bot_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("depends_on", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column("budget", sa.JSON(), nullable=True),
        sa.Column("cost", sa.JSON(), nullable=True),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["sbot_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["sbot_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id", "mission_id"),
    )
    op.create_index(op.f("ix_sbot_mission_nodes_bot_id"), "sbot_mission_nodes", ["bot_id"], unique=False)
    op.create_index("ix_sbot_mission_nodes_lease", "sbot_mission_nodes", ["lease_expires_at"], unique=False)
    op.create_index(
        op.f("ix_sbot_mission_nodes_mission_id"), "sbot_mission_nodes", ["mission_id"], unique=False
    )
    op.create_index(
        "ix_sbot_mission_nodes_mission_status", "sbot_mission_nodes", ["mission_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_column("users", "sbot_heartbeat_next_at")
    op.drop_column("users", "sbot_heartbeat_interval_seconds")
    op.drop_table("sbot_mission_nodes")
    op.drop_table("sbot_mission_blackboard")
    op.drop_table("sbot_missions")
    op.drop_table("sbot_messages")
    op.drop_table("sbot_bot_chat_groups")
    op.drop_table("sbot_sessions")
    op.drop_table("sbot_blueprint_versions")
    op.drop_table("sbot_shares")
    op.drop_table("sbot_schedules")
    op.drop_table("sbot_memories")
    op.drop_table("sbot_bots")
    op.drop_table("sbot_blueprints")
    op.drop_table("sbot_feedback")
    for name in ("user_groups", "users"):
        op.drop_column(name, "project_container_limit")
        op.drop_column(name, "project_containers_enabled")
