"""feedback table

Revision ID: f4200f12107c
Revises: f362c5064a20
Create Date: 2026-07-04 11:14:55.406743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4200f12107c'
down_revision: Union[str, None] = 'f362c5064a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('signal', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('message_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_index('ix_feedback_user_time', 'feedback', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_time', table_name='feedback')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
